def test_004_verify_take_loan(common_page, login_page, home_page, loan_page) -> None:
    login_page.login("user1", "pass1")
    home_page.access_menu("Empréstimos")
    loan_page.select_mount_loan("5.000,00")
    loan_page.take_loan_click()
    common_page.assert_text("A transação foi concluída com sucesso. Você pode voltar para a página principal e continuar suas operações.")
    common_page.back_home()
    common_page.assert_text("10.000,00")
    home_page.access_menu("Empréstimos")
    common_page.assert_text("Você já tem um empréstimo contratado em andamento. Novos empréstimos não estão disponíveis.")
